DOMAIN,c15.youboranqs01.com
DOMAIN,a-fds.youborafds01.com
DOMAIN,infinity-c37.youboranqs01.com
DOMAIN,linear-abematv.akamaized.net
DOMAIN,api-abematv.bucketeer.jp
DOMAIN-SUFFIX,youboranqs01.com
DOMAIN-SUFFIX,youborafds01.com
DOMAIN-KEYWORD,abema
DOMAIN-KEYWORD,youbora
