DOMAIN,motd.ubuntu.com
DOMAIN,ds-cdn.prod-east.frontend.public.atl-paas.net
DOMAIN,d3e54v103j8qbb.cloudfront.net
DOMAIN-SUFFIX,ai
DOMAIN-SUFFIX,clau.de
DOMAIN-SUFFIX,githubcopilot.com
DOMAIN-SUFFIX,browser-intake-datadoghq.com
DOMAIN-SUFFIX,browser-intake-us5-datadoghq.com
DOMAIN-SUFFIX,snapcraft.io
DOMAIN-SUFFIX,hsforms.net
DOMAIN-SUFFIX,revenuecat.com
DOMAIN-SUFFIX,8-lives-cat.io
DOMAIN-SUFFIX,prodregistryv2.org
DOMAIN-SUFFIX,honeycomb.io
DOMAIN-SUFFIX,siftscience.com
DOMAIN-SUFFIX,typekit.net
DOMAIN-SUFFIX,citizenstel.com
DOMAIN-SUFFIX,everesttelecom.com
DOMAIN-SUFFIX,nuvox.com
DOMAIN-SUFFIX,redventures.io
DOMAIN-SUFFIX,cohesionapps.com
DOMAIN-SUFFIX,expo.dev
DOMAIN-SUFFIX,mapbox.com
DOMAIN-SUFFIX,segment.io
DOMAIN-SUFFIX,us.sentry.io
DOMAIN-SUFFIX,us-west-2.amazonaws.com
DOMAIN-SUFFIX,shopify.com
DOMAIN-SUFFIX,atl-paas.net
DOMAIN-SUFFIX,ollama.com
DOMAIN-SUFFIX,ollama.ai
DOMAIN-SUFFIX,ingest.us.sentry.io
DOMAIN-SUFFIX,claudeusercontent.com
DOMAIN-SUFFIX,gitkraken.com
DOMAIN-SUFFIX,gitkraken.dev
DOMAIN-SUFFIX,gitclear.com
DOMAIN-SUFFIX,hcaptcha.com
DOMAIN-SUFFIX,terafab.ai
DOMAIN-SUFFIX,oaistatsig.com
DOMAIN-SUFFIX,hubspotonwebflow.com
DOMAIN-SUFFIX,claudemcpcontent.com
DOMAIN-SUFFIX,hyperagent.com
DOMAIN-KEYWORD,oai
DOMAIN-KEYWORD,openai
DOMAIN-KEYWORD,chatgpt
DOMAIN-KEYWORD,claude
DOMAIN-KEYWORD,anthropic
DOMAIN-KEYWORD,antigravity
DOMAIN-KEYWORD,datadoghq
DOMAIN-KEYWORD,browser-intake
DOMAIN-KEYWORD,ollama
DOMAIN-KEYWORD,copilot
DOMAIN-KEYWORD,gitkraken
PROCESS-NAME,*claude*
PROCESS-NAME,*Claude*
PROCESS-NAME,*codex*
PROCESS-NAME,*Codex*
PROCESS-NAME,*agy*
PROCESS-NAME,*antigravity*
PROCESS-NAME,*Antigravity*
PROCESS-NAME,*chatgpt*
PROCESS-NAME,*ChatGPT*
PROCESS-NAME,*gemini*
PROCESS-NAME,*Gemini*
PROCESS-NAME,*openai*
PROCESS-NAME,*OpenAI*
PROCESS-NAME,*anthropic*
PROCESS-NAME,*Anthropic*
PROCESS-NAME,*ollama*
PROCESS-NAME,*Ollama*
PROCESS-NAME,/Applications/Claude.app/
PROCESS-NAME,/Applications/ChatGPT.app/
PROCESS-NAME,/Applications/Gemini.app/
PROCESS-NAME,/Applications/Codex.app/
PROCESS-NAME,/Applications/Antigravity.app/
PROCESS-NAME,/Applications/Ollama.app/
