DOMAIN-SUFFIX,ai
DOMAIN-SUFFIX,githubcopilot.com
DOMAIN-SUFFIX,browser-intake-us5-datadoghq.com
DOMAIN-SUFFIX,snapcraft.io
DOMAIN-SUFFIX,hsforms.net
DOMAIN-KEYWORD,openai
DOMAIN-KEYWORD,chatgpt
DOMAIN-KEYWORD,claude
DOMAIN-KEYWORD,anthropic
DOMAIN-KEYWORD,datadoghq
DOMAIN-KEYWORD,browser-intake
PROCESS-NAME,Claude
PROCESS-NAME,OpenAI
PROCESS-NAME,ChatGPT
PROCESS-NAME,Codex
