DOMAIN-SUFFIX,ai
DOMAIN-SUFFIX,githubcopilot.com
DOMAIN-SUFFIX,browser-intake-us5-datadoghq.com
DOMAIN-KEYWORD,openai
DOMAIN-KEYWORD,chatgpt
DOMAIN-KEYWORD,claude
DOMAIN-KEYWORD,anthropic
DOMAIN-KEYWORD,datadoghq
DOMAIN-KEYWORD,browser-intake
PROCESS-NAME,claude
PROCESS-NAME,openai
PROCESS-NAME,chatgpt
PROCESS-NAME,codex
