DOMAIN-SUFFIX,akadns.net
DOMAIN-SUFFIX,akamai.net
DOMAIN-SUFFIX,akamai-staging.net
DOMAIN-SUFFIX,akamaiedge.net
DOMAIN-SUFFIX,akamaiedge-staging.net
DOMAIN-SUFFIX,akamaihd.net
DOMAIN-SUFFIX,akamaihd-staging.net
DOMAIN-SUFFIX,akamaiorigin.net
DOMAIN-SUFFIX,akamaiorigin-staging.net
DOMAIN-SUFFIX,akamaized.net
DOMAIN-SUFFIX,akamaized-staging.net
DOMAIN-SUFFIX,edgekey.net
DOMAIN-SUFFIX,edgekey-staging.net
DOMAIN-SUFFIX,edgesuite.net
DOMAIN-SUFFIX,edgesuite-staging.net
DOMAIN-SUFFIX,akam.net
DOMAIN-SUFFIX,akab.net
DOMAIN-SUFFIX,akadns6.net
DOMAIN-SUFFIX,akaetp.net
DOMAIN-SUFFIX,akanev.net
DOMAIN-SUFFIX,akasecure.net
DOMAIN-SUFFIX,akamai.com
DOMAIN-SUFFIX,akamai-access.com
DOMAIN-SUFFIX,akamai-zt.com
DOMAIN-SUFFIX,akamaiapis.net
DOMAIN-SUFFIX,akamaietp.net
DOMAIN-SUFFIX,akamaitechnologies.com
DOMAIN-SUFFIX,aktrials.com
DOMAIN-SUFFIX,akamaietpmitmbypasstest.com
DOMAIN-SUFFIX,etp-research.info
DOMAIN-KEYWORD,akamai
DOMAIN-WILDCARD,aka*.net
IP-ASN,20940,no-resolve
IP-ASN,16625,no-resolve
IP-ASN,32787,no-resolve
IP-ASN,20189,no-resolve
IP-ASN,23454,no-resolve
