DOMAIN-SUFFIX,aws
DOMAIN-SUFFIX,ss2.us
DOMAIN-KEYWORD,amazon
PROCESS-NAME,Prime*
PROCESS-NAME,/Applications/Prime Video.app/
IP-ASN,16509,no-resolve
IP-ASN,7224,no-resolve
IP-ASN,14618,no-resolve
IP-ASN,10291,no-resolve
