DOMAIN-SUFFIX,aws
DOMAIN-SUFFIX,amazon
DOMAIN-SUFFIX,ss2.us
DOMAIN-SUFFIX,amazon.fastly-edge.com
DOMAIN-SUFFIX,awstrack.me
DOMAIN-KEYWORD,aws
DOMAIN-KEYWORD,amazon
PROCESS-NAME,Prime Video
PROCESS-NAME,/Applications/Prime Video.app/
IP-ASN,16509,no-resolve
IP-ASN,14618,no-resolve
IP-ASN,7224,no-resolve
IP-ASN,19047,no-resolve
IP-ASN,62785,no-resolve
IP-ASN,8987,no-resolve
