DOMAIN,qbittorrent.github.io
DOMAIN-SUFFIX,qbittorrent.org
DOMAIN-SUFFIX,transmissionbt.com
DOMAIN-SUFFIX,acgtracker.com
DOMAIN-SUFFIX,fosshub.com
DOMAIN-SUFFIX,bittorrent.com
DOMAIN-SUFFIX,libtorrent.org
