DOMAIN-SUFFIX,juejin.cn
DOMAIN-SUFFIX,linux.do
DOMAIN-SUFFIX,ldstatic.com
PROCESS-NAME,NeteaseMusic
PROCESS-NAME,TencentMeeting
PROCESS-NAME,/Applications/NeteaseMusic.app/
PROCESS-NAME,/Applications/TencentMeeting.app/
