DOMAIN-SUFFIX,juejin.cn
PROCESS-NAME,NeteaseMusic
PROCESS-NAME,TencentMeeting
PROCESS-NAME,qbittorrent
PROCESS-NAME,/Applications/NeteaseMusic.app/
PROCESS-NAME,/Applications/TencentMeeting.app/
PROCESS-NAME,/Applications/qbittorrent.app/
