IP-ASN,11251,no-resolve
IP-ASN,23344,no-resolve
IP-ASN,22604,no-resolve
IP-ASN,398849,no-resolve
IP-ASN,8137,no-resolve
IP-ASN,54330,no-resolve
IP-ASN,29736,no-resolve
IP-ASN,25932,no-resolve
IP-ASN,36863,no-resolve
IP-ASN,140693,no-resolve
