DOMAIN-SUFFIX,threads.com
DOMAIN-SUFFIX,threads.net
DOMAIN-KEYWORD,threads
DOMAIN-KEYWORD,messenger
DOMAIN-KEYWORD,whatsapp
DOMAIN-KEYWORD,instagram
DOMAIN-KEYWORD,insta
IP-ASN,32934,no-resolve
IP-ASN,63293,no-resolve
IP-ASN,54115,no-resolve
IP-ASN,43181,no-resolve
IP-ASN,11070,no-resolve
IP-ASN,35908,no-resolve
IP-ASN,133215,no-resolve
IP-ASN,264010,no-resolve
