DOMAIN-SUFFIX,threads.com
DOMAIN-SUFFIX,threads.net
DOMAIN-SUFFIX,giphy.com
DOMAIN-SUFFIX,metamail.com
DOMAIN-SUFFIX,metaforbusiness.com
DOMAIN-SUFFIX,questfrommeta.com
DOMAIN-SUFFIX,facebookfrommeta.com
DOMAIN-SUFFIX,instagramfrommeta.com
DOMAIN-SUFFIX,whatsappfrommeta.com
DOMAIN-SUFFIX,jobsatmeta.com
DOMAIN-SUFFIX,meta.day
DOMAIN-KEYWORD,meta
DOMAIN-KEYWORD,facebook
DOMAIN-KEYWORD,instagram
DOMAIN-KEYWORD,whatsapp
DOMAIN-KEYWORD,messenger
DOMAIN-KEYWORD,threads
IP-ASN,32934,no-resolve
IP-ASN,63293,no-resolve
IP-ASN,54115,no-resolve
IP-ASN,43181,no-resolve
IP-ASN,11070,no-resolve
