IP-ASN,8075,no-resolve
IP-ASN,8068,no-resolve
IP-ASN,8069,no-resolve
IP-ASN,8070,no-resolve
IP-ASN,12076,no-resolve
IP-ASN,3598,no-resolve
IP-ASN,23468,no-resolve
IP-ASN,22692,no-resolve
IP-ASN,25796,no-resolve
IP-ASN,20046,no-resolve
IP-ASN,397096,no-resolve
IP-ASN,5761,no-resolve
IP-ASN,26222,no-resolve
