DOMAIN-SUFFIX,sl916.com
DOMAIN-SUFFIX,wetest.net
DOMAIN-SUFFIX,cco.moe
DOMAIN-SUFFIX,eva.cm
DOMAIN-SUFFIX,ghcr.io
DOMAIN-SUFFIX,dmhy.org
DOMAIN-SUFFIX,mikanani.me
DOMAIN-SUFFIX,nyaa.si
DOMAIN-SUFFIX,bamgumi.moe
DOMAIN-SUFFIX,acg.rip
DOMAIN-SUFFIX,baidubaidu.win
DOMAIN-SUFFIX,mesl.cloud
DOMAIN-SUFFIX,yingtaowangluo.net
DOMAIN-SUFFIX,woozooo.com
DOMAIN-SUFFIX,chitanda-eru.com
DOMAIN-KEYWORD,lanzou
DOMAIN-REGEX,^(.+\.)?lanzou[a-z]?\.com$
