DOMAIN-SUFFIX,snap.com
DOMAIN-SUFFIX,snapchat.com
DOMAIN-SUFFIX,snapads.com
DOMAIN-SUFFIX,snapkit.co
DOMAIN-SUFFIX,snapkit.com
DOMAIN-SUFFIX,sc-cdn.net
DOMAIN-SUFFIX,sc-gw.com
DOMAIN-SUFFIX,sc-static.net
DOMAIN-SUFFIX,sc-prod.net
DOMAIN-SUFFIX,sc-corp.net
DOMAIN-SUFFIX,spectacles.com
DOMAIN-SUFFIX,snap-dev.net
DOMAIN-SUFFIX,sc-jpl.com
DOMAIN-KEYWORD,snap
IP-CIDR,104.193.185.0/24,no-resolve
IP-CIDR,204.154.248.0/24,no-resolve
IP-CIDR,204.154.250.0/24,no-resolve
IP-ASN,395291,no-resolve
