IP-ASN,33353,no-resolve
IP-ASN,11795,no-resolve
IP-ASN,25562,no-resolve
IP-ASN,55901,no-resolve
IP-ASN,397077,no-resolve
IP-ASN,2527,no-resolve
IP-ASN,9600,no-resolve
IP-ASN,3725,no-resolve
IP-ASN,19419,no-resolve
IP-ASN,25181,no-resolve
IP-ASN,38258,no-resolve
IP-ASN,9619,no-resolve
IP-ASN,33064,no-resolve
IP-ASN,139808,no-resolve
