DOMAIN-SUFFIX,sumsub.com
DOMAIN-SUFFIX,fragment.com
DOMAIN-SUFFIX,tonkeeper.com
DOMAIN-SUFFIX,ton.org
DOMAIN-SUFFIX,tonapi.io
DOMAIN-KEYWORD,telegraph
DOMAIN-KEYWORD,telegram
PROCESS-NAME,Telegram
PROCESS-NAME,/Applications/Telegram.app/
