DOMAIN-SUFFIX,ttwstatic.com
DOMAIN-SUFFIX,pitaya-clientai.com
DOMAIN-SUFFIX,tiktok-row.net
DOMAIN-SUFFIX,tiktokcdn-eu.com
DOMAIN-SUFFIX,tiktokcdn-us.com
DOMAIN-SUFFIX,frfigures.com
DOMAIN-SUFFIX,tiktokshop.com
DOMAIN-SUFFIX,ismcdn.jp
DOMAIN-KEYWORD,tiktok
DOMAIN-KEYWORD,tiktokcdn
DOMAIN-KEYWORD,ttw
DOMAIN-KEYWORD,ibyte
IP-CIDR,66.51.70.36/32,no-resolve
IP-CIDR,45.197.88.8/32,no-resolve
IP-CIDR,103.47.200.166/32,no-resolve
IP-CIDR,38.211.116.7/32,no-resolve
IP-CIDR,66.51.70.4/32,no-resolve
IP-ASN,396986,no-resolve
IP-ASN,138699,no-resolve
IP-ASN,11983,no-resolve
IP-ASN,150436,no-resolve
