DOMAIN-SUFFIX,grokipedia.com
DOMAIN-SUFFIX,spacex.com
DOMAIN-SUFFIX,starlink.com
DOMAIN-SUFFIX,tesla.com
DOMAIN-SUFFIX,x.ai
DOMAIN-SUFFIX,grok.com
DOMAIN-KEYWORD,spacex
DOMAIN-KEYWORD,starlink
DOMAIN-KEYWORD,tesla
IP-ASN,13414,no-resolve
IP-ASN,35995,no-resolve
IP-ASN,63179,no-resolve
